apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf-10-100-dep
  namespace: etri6g
  labels:
    nfType: amf
  annotations:
    autoscaling.volantis/state-port: "7001"
    autoscaling.volantis/state-path: "/state"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amf
      app-ex: default
      amfSet: 10-100
  template:
    metadata:
      labels:
        app: amf
        amfSet: 10-100
        plmnId: 001-01
    spec:
      volumes:
        - name: amf-config
          configMap:
            name: amf-10-100-config

      containers:
        - name: amf
          image: ghcr.io/reogac/volantis/amf:v0.1.0
          imagePullPolicy: IfNotPresent
          command: ["./amf"]
          args: ["-c", "/etc/config/amf.json"]
          volumeMounts:
            - mountPath: /etc/config
              name: amf-config
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"

          ports:
            - containerPort: 9001
            - containerPort: 7001

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-10-100-config 
  namespace: etri6g
data:
  amf.json: |
    {
      "plmnId": {
        "mcc": "001",
        "mnc": "01"
      },
      "amfSet":"10-100",
      "mesh": {
        "registrar": "10.100.100.1"
      }
    }

