apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf-dep
  namespace: etri6g
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
        plmnId: 001-01
    spec:
      volumes:
        - name: pcf-config
          configMap:
            name: pcf-config

      containers:
        - name: pcf
          image: ghcr.io/reogac/volantis/pcf:v0.1.0
          imagePullPolicy: IfNotPresent
          command: ["./pcf"]
          args: ["-c", "/etc/config/pcf.json"]
          volumeMounts:
            - mountPath: /etc/config
              name: pcf-config

          ports:
            - containerPort: 9001
            - containerPort: 7001
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config 
  namespace: etri6g
data:
  pcf.json: |
    {
      "plmnId": {
        "mcc": "001",
        "mnc": "01"
      },
      "mesh": {
        "registrar": "10.100.100.1"
      }
    }
